### ISSUE TITLE
link to CDB implementation

### ISSUE THREAD

**Issue by 89z** [volution/kawipiko#4]
"CDB" is mentioned at least 10 times in the readme, but I didnt find a single mention of the implemention used:

https://github.com/volution/kawipiko/blob/86463b58f8da6ab5746da28c9ec009bf2a6dd65a/sources/go.mod#L7

https://github.com/colinmarc/cdb

I think it would be right to add a mention or link to the implementation in the Readme.

**Comment by cipriancraciun** [comment]
Actually the implementation is a custom fork of that library:

https://github.com/volution/kawipiko/blob/86463b58f8da6ab5746da28c9ec009bf2a6dd65a/sources/go.mod#L39

But I've added a mention about all this in the readme.

Thanks for the observation!
